poblacion de base de datos student1
alejandromd/Acme-L3-D02 pull request #143
Opened 2023-03-11 19:31 UTC by alejandromd

2023-03-16 12:26 UTC, goncammej requested changes
Poblado de datos muy pobre. Te recomiendo que le eches un vistazo a las buenas prácticas de las transparencias de teoría.

2023-03-17 09:09 UTC, Thealean28 approved these changes

2023-03-17 09:10 UTC, Thealean28 approved these changes

2023-03-17 09:28 UTC, goncammej approved these changes
Implementación correcta

2023-03-17 09:29 UTC, merged